### PR TITLE
add support for Vertica

### PR DESCRIPTION
**Pull request by lukas-mi**
Added Vertica driver to the dependencies. Tested on Vertica cluster.

### CODE REVIEW

**Comment by dewey** [comment]
Hey @lukas-mi, is this still something you are interested in? If you are, great! I just took over the maintenance a bit so I'm working my way through the backlog. Sorry for the delay.

There's some small changes I'd like to see.

- Please rebase it on the latest master
- Add an example connection string to the example file: https://github.com/justwatchcom/sql_exporter/blob/master/config.yml.dist
- Add Vertica as supported platform to the README

Thanks!

**Comment by bentzimortaboola** [comment]
Vertica latest gp version is 1.2.1 , maybe better to apply latest

**Comment by bentzimortaboola** [comment]
I have verified and it working fine

**Comment by dewey** [comment]
@bentzimortaboola Thanks, let's see if the PR gets updated. Otherwise I'll have to take a look in a few days.

**Comment by lukas-mi** [comment]
Updated the PR @dewey

**Comment by dewey** [comment]
@lukas-mi Thanks a lot for the contribution! I'm going to prepare a new release after that is in master.

**Pull request merged**
