### PR TITLE
feat: add support for scheduling jobs using cron syntax

### PR DESCRIPTION
**Pull request by FUSAKLA**
Instead of https://github.com/justwatchcom/sql_exporter/pull/30 implementing the CRON scheduling as suggested by @dewey 

Not sure about the configuration if the precedence of the `cron_schedule` is ok or should bail out if both is configured?

PTAL

### CODE REVIEW

**Comment by FUSAKLA** [comment]
Possibly @dominikschulz :eyes:

**Comment by dewey** [comment]
Thanks for the PR. I'm going to take a look early next week :)

**Comment by FUSAKLA** [comment]
Great, thanks! 

not sure about the vendoring issue in CI, locally `go build -v ./...` basses with no issues and the cron library is vendored :thinking:

**Comment by FUSAKLA** [comment]
@dewey friendly bump in case you may have forgotten?

**Comment by dewey** [comment]
Hey @FUSAKLA, not forgotten, just busy :) 

I just tried it locally and I'm getting the same error as CI. The robfig cron library is not vendored that's why it doesn't work. Can you run a `go mod vendor`?

```
sql_exporter|fus-cronjob ⇒ go build -v ./...
config.go:16:2: cannot find package "." in:
	/Users/philippdefner/mod/github.com/justwatchcom/sql_exporter/vendor/github.com/robfig/cron/v3
```

**Comment by FUSAKLA** [comment]
:facepalm: I had a `vendor` ignored by the global git config. Sorry my bad.
Should be fixed now.

**Comment by dewey** [comment]
Looks good now @FUSAKLA. Thanks for the feature!

**Comment by FUSAKLA** [comment]
Thanks for accepting it! :)

**Pull request merged**
