### PR TITLE
Do not attempt to parse MySQL DSNs as URLs

### PR DESCRIPTION
**Pull request by matthiasr**
they do not conform to the RFCs for web URLs, and Go 1.12.8+ enforce
this.

Instead of the parsed URL, keep the original connection string.

This could probably be generalized for other databases, but I don't know
if they have the same problem.

Signed-off-by: Matthias Rampke <mr@soundcloud.com>

### CODE REVIEW

**Comment by marthjod** [comment]
Thanks for this.

Note to self: Evaluate https://github.com/xo/dburl.

**Comment by marthjod** [comment]
Integrated into master. Thank you for the MR.

**Comment by razitz** [comment]
Hey @marthjod, any chance for a new release with this fix?

**Comment by marthjod** [comment]
Here you go: https://github.com/justwatchcom/sql_exporter/releases/tag/v0.4.0.

**Pull request closed without merging**
