### PR TITLE
Add synchronous jobs

### PR DESCRIPTION
**Pull request by xxorde**
We needed a possibility to execute some jobs / queries synchronous every time /metrics is requested.
So I added the infrastructure to execute jobs with an interval <=0 synchronous when the http-handler is called.

```
interval: '0s' # an interval <= 0 will make the queries synchronous
```

I hope my patch does not brings any drawback, just had to change some parts after importing your current version.

It would be great if you are interested in this feature and we could start a discussion.

### CODE REVIEW

**Comment by xxorde** [comment]
@dominikschulz what do you think about the feature in general and my patch?

**Comment by dominikschulz** [comment]
Sorry for the long delay. I was thinking about this PR a few times already, but I don't really like the current approach. It feels to hacky, adding too many special cases.

We understand the need for synchronous queries, but I'd like to finde a may the feels more natural.

**Comment by bobrik** [comment]
I'd really love to see synchronous queries. Async queries can easily misalign with scraping intervals and cause steady rates to appear as sawtooth.

**Comment by xxorde** [comment]
@dominikschulz  I would really appreciate if you can find a more cleaner way to do this. For someone how is a more experienced developer and knows the involved libraries it might just be a few lines of code. There is not much logic involved.

What do you think about the way to identify a synchronous job by setting the interval to '0' ?

@bobrik that was our problem and the intention to add that feature!

**Comment by ChristophBerg** [comment]
I just pushed a rebased and polished up version of this patch to the original location. (Sorry for deleting it some time ago.) It now also updates the README file to mention interval 0.
Could you maybe have another look to see if it fits your idea, or what would need changing?
We are running this patch in https://github.com/credativ/elephant-shed and would love to see it merged.
Thanks!

**Comment by df7cb** [comment]
Fwiw, #51 is about snowflake support, not synchronous jobs, so this PR should have been left open.

**Comment by dewey** [comment]
Thanks, I'll take a look what went wrong there :\

**Comment by mbanck-ntap** [comment]
I have re-submitted this as #131 now as untangling this one looks difficult.

**Comment by dewey** [comment]
Thank you, much appreciated! I had a hard time to figure out how to undo that.

**Pull request merged**
